// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const url = process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"];
console.log("DEBUG: Prisma Config Datasource URL:", url);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url,
  },
});
